# Generated by Django 5.1.4 on 2024-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cm_hex_address',
            field=models.CharField(blank=True, max_length=150, verbose_name='cm hex address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cm_private_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='cm private key'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cm_public_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='cm public key'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cm_wallet',
            field=models.CharField(blank=True, max_length=150, verbose_name='cm wallet address'),
        ),
    ]
