# Generated by Django 5.1.4 on 2025-01-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_cm_hex_address_customuser_cm_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active_for_hour',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active_for_while',
            field=models.BooleanField(default=False),
        ),
    ]
