# Generated by Django 5.1.4 on 2025-01-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_is_active_for_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active_for_while',
        ),
    ]
