# Generated by Django 5.1.4 on 2025-01-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_is_active_for_while'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_activated',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_enabled_time',
        ),
    ]
