# Generated by Django 5.1.4 on 2025-01-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=10),
        ),
    ]
