# Generated by Django 5.1.4 on 2024-12-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
