# Generated by Django 5.1.4 on 2025-01-09 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
