# Generated by Django 5.1.4 on 2025-01-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_usage_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usage',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='usage',
            name='fee',
        ),
        migrations.AddField(
            model_name='usage',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
