# Generated by Django 5.1.4 on 2025-01-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_alter_usage_options_remove_usage_fee_usage_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='agent_os',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usage',
            name='http_referer',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usage',
            name='http_user_agent',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usage',
            name='http_x_forwarded_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
