# Generated by Django 5.1.4 on 2024-12-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_investment', models.IntegerField()),
                ('max_investment', models.IntegerField()),
                ('fee_percentage', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
