# Generated by Django 5.1.4 on 2025-01-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
