# Generated by Django 5.1.4 on 2025-01-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_fee_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['min_investment']},
        ),
    ]
