# Generated by Django 5.1.4 on 2025-01-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_fee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_investment', models.IntegerField()),
                ('max_investment', models.IntegerField()),
                ('fee_percentage', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'ordering': ['min_investment'],
            },
        ),
    ]
