# Generated by Django 5.1.4 on 2025-01-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execute',
            name='amount',
            field=models.FloatField(),
        ),
    ]
