# Generated by Django 5.1.4 on 2025-01-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='wallet address'),
        ),
    ]
