# Generated by Django 5.1.4 on 2025-01-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='user',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Withdraw',
        ),
    ]
