# Generated by Django 5.1.4 on 2025-01-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emailaddress_idx_upper_email'),
        ('authentication', '0002_emailverificationcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='email_address',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='verification_code', to='account.emailaddress', verbose_name='email address'),
            preserve_default=False,
        ),
    ]
